import {
  MONGO_DATABASE,
  MONGO_DB_PASS,
  MONGO_URL_FIRST,
  MONGO_URL_SECOND,
  MONGO_URL_THIRD,
} from './env';

export const MONGODB_URI = `${MONGO_URL_FIRST}${MONGO_DB_PASS}${MONGO_URL_SECOND}${MONGO_DATABASE}${MONGO_URL_THIRD}`;
